In [1]:
from google.colab import files
uploaded = files.upload()

Saving Small Finance bank (5).xlsx to Small Finance bank (5).xlsx

In [2]:
import pandas as pd

file_name = "Small Finance bank (5).xlsx"
xls = pd.ExcelFile(file_name)

xls.sheet_names

['summary ',
 'Au Small Finance Bank',
 'Capital Small Finance Bank',
 'ESAF Small Finance Bank',
 'Equitas Small Finance Bank',
 'Jana Small Finance Bank',
 'Suryoday Small Finance Bank',
 'Ujjivan Small Finance Bank',
 'Utkarsh Small Finance Bank']

In [4]:
df = pd.read_excel(file_name, sheet_name="summary")
df.head()

ValueError: Worksheet named 'summary' not found

In [5]:
xls = pd.ExcelFile(file_name)

for s in xls.sheet_names:
    print(repr(s))

'summary '
'Au Small Finance Bank'
'Capital Small Finance Bank'
'ESAF Small Finance Bank'
'Equitas Small Finance Bank'
'Jana Small Finance Bank'
'Suryoday Small Finance Bank'
'Ujjivan Small Finance Bank'
'Utkarsh Small Finance Bank'

In [6]:
df = pd.read_excel(file_name, sheet_name='summary ')

In [7]:
df = pd.read_excel(file_name, sheet_name=xls.sheet_names[0])

df.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Ratio analysis,Au Small Finance Bank,Capital Small Finance Bank,ESAF Small Finance Bank,Jana Small Finance Bank,Suryoday Small Finance Bank,Ujjivan Small Finance Bank,Utkarsh Small Finance Bank
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df = pd.read_excel(
    file_name,
    sheet_name=xls.sheet_names[0],
    header=2
)

df.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,Ratio analysis,Au Small Finance Bank,Capital Small Finance Bank,ESAF Small Finance Bank,Jana Small Finance Bank,Suryoday Small Finance Bank,Ujjivan Small Finance Bank,Utkarsh Small Finance Bank
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Revenue growth (YoY),0.005023,0.15421,-0.084159,0.136541,0.105715,0.090813,-0.102565

In [9]:
df.head(15)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,Ratio analysis,Au Small Finance Bank,Capital Small Finance Bank,ESAF Small Finance Bank,Jana Small Finance Bank,Suryoday Small Finance Bank,Ujjivan Small Finance Bank,Utkarsh Small Finance Bank
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Revenue growth (YoY),0.005023,0.15421,-0.084159,0.136541,0.105715,0.090813,-0.102565
5,Gross margin,0.488974,0.440034,0.480535,0.484437,0.508594,0.558469,0.437063
6,EBITDA margin,0.697439,0.6463,0.225601,0.385638,0.417296,0.413183,-0.010519
7,PBT margin,0.186413,0.18005,-0.064571,0.060982,0.092381,0.131434,-0.445904
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,current ratio/quick ratio,1.260531,2.488512,2.29612,1.438142,2.486391,2.192116,1.016496
11,Debt equity ratio,8.439398,7.198401,16.068684,9.311063,8.23569,7.353697,8.998048
12,Return on net worth/ROE,0.133851,0.096774,-0.093481,0.073627,0.073122,0.103096,-0.423
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Inventory Turnover days,0,0,0,0,0,0,0

In [10]:
df = df.dropna(how='all')

In [11]:
df = df.rename(columns={df.columns[0]: "Metric"})

In [12]:
df = df[df["Metric"].notna()]

In [13]:
df_long = df.melt(
    id_vars="Metric",
    var_name="Bank",
    value_name="Value"
)

In [14]:
df_long = df_long.dropna()

In [15]:
df_long.head(20)

                       Metric        Bank                       Value
0              Ratio analysis  Unnamed: 1       Au Small Finance Bank
1        Revenue growth (YoY)  Unnamed: 1                    0.005023
2                Gross margin  Unnamed: 1                    0.488974
3               EBITDA margin  Unnamed: 1                    0.697439
4                  PBT margin  Unnamed: 1                    0.186413
5   current ratio/quick ratio  Unnamed: 1                    1.260531
6           Debt equity ratio  Unnamed: 1                    8.439398
7     Return on net worth/ROE  Unnamed: 1                    0.133851
8     Inventory Turnover days  Unnamed: 1                           0
9   Receivables Turnover days  Unnamed: 1                           0
10     Payables Turnover days  Unnamed: 1                           0
11       Net WC turnover days  Unnamed: 1                           0
12                        ROA  Unnamed: 1                    0.069781
13                       EBIT  Unnamed: 1                    12997.71
14            Tangible assets  Unnamed: 1                           0
15          Intangible assets  Unnamed: 1                           0
16         Net Current Assets  Unnamed: 1                     1441.26
17       WC debt as a % of WC  Unnamed: 1                    0.206684
18             Ratio analysis  Unnamed: 2  Capital Small Finance Bank
19       Revenue growth (YoY)  Unnamed: 2                     0.15421

In [16]:
import streamlit as st
import pandas as pd
import plotly.express as px

st.set_page_config(page_title="SFB Financial Dashboard", layout="wide")

st.title("Small Finance Bank Financial Dashboard")

df = pd.read_csv("cleaned_sfb_data.csv")

banks = st.multiselect(
    "Select Banks",
    options=df["Bank"].unique(),
    default=df["Bank"].unique()[:3]
)

metric = st.selectbox(
    "Select Metric",
    options=df["Metric"].unique()
)

filtered = df[
    (df["Bank"].isin(banks)) &
    (df["Metric"] == metric)
]

col1, col2, col3 = st.columns(3)

col1.metric("Selected Banks", len(banks))
col2.metric("Selected Metric", metric)
col3.metric("Average Value", round(filtered["Value"].mean(), 4))

fig = px.bar(
    filtered,
    x="Bank",
    y="Value",
    color="Bank",
    title=f"{metric} Comparison"
)

st.plotly_chart(fig, use_container_width=True)

st.subheader("Data Table")
st.dataframe(filtered)

ModuleNotFoundError: No module named 'streamlit'

In [17]:
!pip install streamlit

Collecting streamlit
  Downloading streamlit-1.57.0-py3-none-any.whl.metadata (9.6 kB)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<8,>=5.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.2.6)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (8.3.3)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.12/dist-packages (from streamlit) (3.1.47)
Requirement already satisfied: numpy<3,>=1.23 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.0.2)
Requirement already satisfied: packaging>=20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (26.1)
Requirement already satisfied: pandas<4,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.2.2)
Requirement already satisfied: pillow<13,>=7.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (11.3.0)
Collecting pydeck<1,>=0.8.0b4 (from streamlit)
  Downloading pydeck-0.9.2-py2.py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: protobuf<8,>=3.20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.29.6)
Requirement already satisfied: pyarrow>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (18.1.0)
Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.32.4)
Requirement already satisfied: tenacity<10,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (9.1.4)
Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.15.0)
Requirement already satisfied: starlette>=0.40.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.52.1)
Requirement already satisfied: uvicorn>=0.30.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.46.0)
Requirement already satisfied: httptools>=0.6.3 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.7.1)
Requirement already satisfied: anyio>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.13.0)
Requirement already satisfied: python-multipart>=0.0.10 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.0.26)
Requirement already satisfied: websockets>=12.0.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (15.0.1)
Requirement already satisfied: itsdangerous>=2.1.2 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.2.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.0.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (4.26.0)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2.20.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio>=4.0.0->streamlit) (3.13)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit) (2026.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2026.4.22)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.12/dist-packages (from uvicorn>=0.30.0->streamlit) (0.16.0)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.3)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.30.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<4,>=1.4.0->streamlit) (1.17.0)
Downloading streamlit-1.57.0-py3-none-any.whl (9.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.2/9.2 MB 77.4 MB/s eta 0:00:00
Downloading pydeck-0.9.2-py2.py3-none-any.whl (11.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.3/11.3 MB 82.1 MB/s eta 0:00:00
Installing collected packages: pydeck, streamlit
Successfully installed pydeck-0.9.2 streamlit-1.57.0

In [18]:
import streamlit as st
import pandas as pd
import plotly.express as px

st.set_page_config(page_title="SFB Financial Dashboard", layout="wide")

st.title("Small Finance Bank Financial Dashboard")

df = pd.read_csv("cleaned_sfb_data.csv")

banks = st.multiselect(
    "Select Banks",
    options=df["Bank"].unique(),
    default=df["Bank"].unique()[:3]
)

metric = st.selectbox(
    "Select Metric",
    options=df["Metric"].unique()
)

filtered = df[
    (df["Bank"].isin(banks)) &
    (df["Metric"] == metric)
]

col1, col2, col3 = st.columns(3)

col1.metric("Selected Banks", len(banks))
col2.metric("Selected Metric", metric)
col3.metric("Average Value", round(filtered["Value"].mean(), 4))

fig = px.bar(
    filtered,
    x="Bank",
    y="Value",
    color="Bank",
    title=f"{metric} Comparison"
)

st.plotly_chart(fig, use_container_width=True)

st.subheader("Data Table")
st.dataframe(filtered)

2026-05-26 04:49:45.392 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 04:49:45.399 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 04:49:45.987
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run /usr/local/lib/python3.12/dist-packages/colab_kernel_launcher.py [ARGUMENTS]
2026-05-26 04:49:45.988 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 04:49:45.998 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

FileNotFoundError: [Errno 2] No such file or directory: 'cleaned_sfb_data.csv'

In [19]:
df_long.to_csv("cleaned_sfb_data.csv", index=False)

In [20]:
import os
os.listdir()

['.config',
 'cleaned_sfb_data.csv',
 'Small Finance bank (5).xlsx',
 'sample_data']

In [47]:
import streamlit as st
import pandas as pd
import plotly.express as px

st.set_page_config(page_title="SFB Financial Dashboard", layout="wide")

st.title("Small Finance Bank Financial Dashboard")

df = pd.read_csv("cleaned_sfb_data.csv")

# Clean text
df["Bank"] = df["Bank"].astype(str).str.strip()
df["Metric"] = df["Metric"].astype(str).str.strip()

# Sidebar filters
st.sidebar.header("Filters")

selected_banks = st.sidebar.multiselect(
    "Select Banks",
    options=sorted(df["Bank"].unique()),
    default=sorted(df["Bank"].unique())
)

selected_metric = st.sidebar.selectbox(
    "Select Metric",
    options=sorted(df["Metric"].unique())
)

filtered = df[
    (df["Bank"].isin(selected_banks)) &
    (df["Metric"] == selected_metric)
].copy()

tab1, tab2, tab3, tab4 = st.tabs(
    ["Overview", "Bank Comparison", "Rankings", "Raw Data"]
)

with tab1:
    st.subheader("Dashboard Overview")

    col1, col2, col3, col4 = st.columns(4)

    col1.metric("Selected Banks", len(selected_banks))
    col2.metric("Selected Metric", selected_metric)
    col3.metric("Average Value", round(filtered["Value"].mean(), 4))
    col4.metric("Highest Value", round(filtered["Value"].max(), 4))

    st.write("This dashboard compares Small Finance Banks across key financial ratios and performance metrics.")

    fig = px.bar(
        filtered,
        x="Bank",
        y="Value",
        color="Bank",
        title=f"{selected_metric} Comparison"
    )
    st.plotly_chart(fig, use_container_width=True)

with tab2:
    st.subheader("Bank Comparison")

    chart_type = st.radio(
        "Select Chart Type",
        ["Bar Chart", "Line Chart"],
        horizontal=True
    )

    if chart_type == "Bar Chart":
        fig = px.bar(
            filtered,
            x="Bank",
            y="Value",
            color="Bank",
            title=f"{selected_metric} - Bank Wise Comparison"
        )
    else:
        fig = px.line(
            filtered,
            x="Bank",
            y="Value",
            markers=True,
            title=f"{selected_metric} Trend Across Banks"
        )

    st.plotly_chart(fig, use_container_width=True)

    st.subheader("Metric Heatmap")

    heatmap_df = df[df["Bank"].isin(selected_banks)].pivot_table(
        index="Bank",
        columns="Metric",
        values="Value",
        aggfunc="mean"
    )

    fig_heatmap = px.imshow(
        heatmap_df,
        text_auto=True,
        aspect="auto",
        title="Bank vs Metric Heatmap"
    )

    st.plotly_chart(fig_heatmap, use_container_width=True)

with tab3:
    st.subheader("Rankings")

    ranking_df = filtered.sort_values("Value", ascending=False)

    col1, col2 = st.columns(2)

    with col1:
        st.write("Top Banks")
        st.dataframe(ranking_df.head(5), use_container_width=True)

    with col2:
        st.write("Bottom Banks")
        st.dataframe(ranking_df.tail(5), use_container_width=True)

    fig_rank = px.bar(
        ranking_df,
        x="Value",
        y="Bank",
        orientation="h",
        color="Bank",
        title=f"Ranking by {selected_metric}"
    )
    st.plotly_chart(fig_rank, use_container_width=True)

with tab4:
    st.subheader("Raw Data")

    st.dataframe(df, use_container_width=True)

    csv = df.to_csv(index=False).encode("utf-8")

    st.download_button(
        label="Download Data as CSV",
        data=csv,
        file_name="sfb_financial_dashboard_data.csv",
        mime="text/csv"
    )

2026-05-26 05:23:21.491 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:21.496 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:21.499 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:21.500 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:21.515 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:21.516 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:21.518 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:21.520 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:21.523 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:21.526 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:21.528 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:21.530 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:21.533 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:21.535 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:21.538 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:21.544 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:21.547 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:21.549 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:21.552 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:21.557 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:21.564 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:21.570 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:21.573 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:21.574 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:21.577 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:21.579 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:21.581 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:21.585 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:21.587 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:21.591 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:21.595 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:21.596 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:21.598 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:21.600 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:21.601 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:21.604 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:21.605 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:21.606 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:21.607 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:21.612 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:21.613 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:21.615 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:21.617 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:21.618 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:21.620 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:21.623 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:21.625 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:21.627 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:21.754 Please replace `use_container_width` with `width`.

`use_container_width` will be removed after 2025-12-31.

For `use_container_width=True`, use `width='stretch'`. For `use_container_width=False`, use `width='content'`.
2026-05-26 05:23:21.765 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:21.769 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:21.776 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:21.776 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:21.780 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:21.785 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:21.787 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:21.788 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:21.789 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:21.790 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:21.791 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:21.791 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:21.793 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:21.795 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:21.801 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:21.897 Please replace `use_container_width` with `width`.

`use_container_width` will be removed after 2025-12-31.

For `use_container_width=True`, use `width='stretch'`. For `use_container_width=False`, use `width='content'`.
2026-05-26 05:23:21.904 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:21.906 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:21.909 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:21.912 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:21.915 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:21.918 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:21.919 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:21.921 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:22.010 Please replace `use_container_width` with `width`.

`use_container_width` will be removed after 2025-12-31.

For `use_container_width=True`, use `width='stretch'`. For `use_container_width=False`, use `width='content'`.
2026-05-26 05:23:22.012 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:22.014 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:22.015 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:22.024 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:22.024 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:22.031 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:22.033 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:22.037 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:22.043 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:22.048 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:22.052 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:22.053 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:22.055 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:22.062 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:22.063 Please replace `use_container_width` with `width`.

`use_container_width` will be removed after 2025-12-31.

For `use_container_width=True`, use `width='stretch'`. For `use_container_width=False`, use `width='content'`.
2026-05-26 05:23:22.070 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:22.078 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:22.086 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:22.088 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:22.089 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:22.094 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:22.099 Please replace `use_container_width` with `width`.

`use_container_width` will be removed after 2025-12-31.

For `use_container_width=True`, use `width='stretch'`. For `use_container_width=False`, use `width='content'`.
2026-05-26 05:23:22.107 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:22.111 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:22.116 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:22.204 Please replace `use_container_width` with `width`.

`use_container_width` will be removed after 2025-12-31.

For `use_container_width=True`, use `width='stretch'`. For `use_container_width=False`, use `width='content'`.
2026-05-26 05:23:22.208 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:22.211 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:22.212 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:22.213 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:22.214 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:22.216 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:22.216 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:22.218 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:22.219 Please replace `use_container_width` with `width`.

`use_container_width` will be removed after 2025-12-31.

For `use_container_width=True`, use `width='stretch'`. For `use_container_width=False`, use `width='content'`.
2026-05-26 05:23:22.222 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:22.223 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:22.224 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:22.227 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:22.229 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:22.229 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:22.230 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:22.232 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:22.233 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:23:22.233 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [23]:
!pip install streamlit pyngrok -q

In [27]:
from pyngrok import ngrok

public_url = ngrok.connect(8501)
print(public_url)

ERROR:pyngrok.process.ngrok:t=2026-05-26T04:57:46+0000 lvl=eror msg="failed to reconnect session" obj=tunnels.session err="authentication failed: Usage of ngrok requires a verified account and authtoken.\n\nSign up for an account: https://dashboard.ngrok.com/signup\nInstall your authtoken: https://dashboard.ngrok.com/get-started/your-authtoken\r\n\r\nERR_NGROK_4018\r\n"

PyngrokNgrokError: The ngrok process errored on start: authentication failed: Usage of ngrok requires a verified account and authtoken.\n\nSign up for an account: https://dashboard.ngrok.com/signup\nInstall your authtoken: https://dashboard.ngrok.com/get-started/your-authtoken\r\n\r\nERR_NGROK_4018\r\n.

In [28]:
!pip install streamlit -q
!npm install -g localtunnel

⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇
added 22 packages in 2s
⠇
⠇3 packages are looking for funding
⠇  run `npm fund` for details
⠇

In [29]:
!pkill -f streamlit

In [32]:
!ls -lah

total 68K
drwxr-xr-x 1 root root 4.0K May 26 04:50  .
drwxr-xr-x 1 root root 4.0K May 26 04:19  ..
-rw-r--r-- 1 root root  909 May 26 04:50  app.py
-rw-r--r-- 1 root root 4.8K May 26 04:50  cleaned_sfb_data.csv
drwxr-xr-x 4 root root 4.0K May 21 13:26  .config
drwxr-xr-x 1 root root 4.0K May 21 13:27  sample_data
-rw-r--r-- 1 root root  39K May 26 04:32 'Small Finance bank (5).xlsx'

In [35]:
!pkill -f streamlit
!pkill -f localtunnel

In [38]:
!wget -q -O cloudflared https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
!chmod +x cloudflared

In [39]:
!pkill -f streamlit

In [40]:
!streamlit run app.py --server.port 8501 --server.address 0.0.0.0 --server.headless true > streamlit.log 2>&1 &

In [42]:
df = pd.read_excel(file_name, sheet_name=xls.sheet_names[0], header=2)

# first row has real bank names
df.columns = df.iloc[0]

# remove that first row
df = df.iloc[1:].reset_index(drop=True)

# rename first column
df = df.rename(columns={df.columns[0]: "Metric"})

# remove empty rows
df = df.dropna(how="all")
df = df[df["Metric"].notna()]

# convert wide to long
df_long = df.melt(
    id_vars="Metric",
    var_name="Bank",
    value_name="Value"
)

df_long = df_long.dropna()
df_long["Value"] = pd.to_numeric(df_long["Value"], errors="coerce")
df_long = df_long.dropna(subset=["Value"])

# save again
df_long.to_csv("cleaned_sfb_data.csv", index=False)

df_long.head()

                      Metric                   Bank     Value
0       Revenue growth (YoY)  Au Small Finance Bank  0.005023
1               Gross margin  Au Small Finance Bank  0.488974
2              EBITDA margin  Au Small Finance Bank  0.697439
3                 PBT margin  Au Small Finance Bank  0.186413
4  current ratio/quick ratio  Au Small Finance Bank  1.260531

In [43]:
!pkill -f streamlit
!streamlit run app.py --server.port 8501 --server.address 0.0.0.0 --server.headless true > streamlit.log 2>&1 &

In [44]:
!cat streamlit.log

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.

2026-05-26 05:13:06.645 Uvicorn server started on 0.0.0.0:8501

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://172.28.0.12:8501
  External URL: http://35.236.227.192:8501

In [48]:
!pkill -f streamlit

In [49]:
!streamlit run app.py --server.port 8501 --server.address 0.0.0.0 --server.headless true > streamlit.log 2>&1 &

In [50]:
!pkill -f streamlit

In [51]:
!streamlit run app.py --server.port 8501 --server.address 0.0.0.0 --server.headless true > streamlit.log 2>&1 &

In [52]:
!cat streamlit.log

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.

2026-05-26 05:24:37.604 Uvicorn server started on 0.0.0.0:8501

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://172.28.0.12:8501
  External URL: http://35.236.227.192:8501

In [54]:
!head -40 app.py

import streamlit as st
import pandas as pd
import plotly.express as px

st.set_page_config(page_title="SFB Financial Dashboard", layout="wide")

st.title("Small Finance Bank Financial Dashboard")

df = pd.read_csv("cleaned_sfb_data.csv")

banks = st.multiselect(
    "Select Banks",
    options=df["Bank"].unique(),
    default=list(df["Bank"].unique()[:3])
)

metric = st.selectbox(
    "Select Metric",
    options=df["Metric"].unique()
)

filtered = df[
    (df["Bank"].isin(banks)) &
    (df["Metric"] == metric)
]

col1, col2, col3 = st.columns(3)
col1.metric("Selected Banks", len(banks))
col2.metric("Selected Metric", metric)
col3.metric("Average Value", round(filtered["Value"].mean(), 4))

fig = px.bar(
    filtered,
    x="Bank",
    y="Value",
    color="Bank",
    title=f"{metric} Comparison"
)

st.plotly_chart(fig, use_container_width=True)

In [55]:
%%writefile app.py

Overwriting app.py

In [56]:
import streamlit as st
import pandas as pd
import plotly.express as px

st.set_page_config(page_title="SFB Financial Dashboard", layout="wide")

st.title("Small Finance Bank Financial Dashboard")

df = pd.read_csv("cleaned_sfb_data.csv")

# Clean text
df["Bank"] = df["Bank"].astype(str).str.strip()
df["Metric"] = df["Metric"].astype(str).str.strip()

# Sidebar filters
st.sidebar.header("Filters")

selected_banks = st.sidebar.multiselect(
    "Select Banks",
    options=sorted(df["Bank"].unique()),
    default=sorted(df["Bank"].unique())
)

selected_metric = st.sidebar.selectbox(
    "Select Metric",
    options=sorted(df["Metric"].unique())
)

filtered = df[
    (df["Bank"].isin(selected_banks)) &
    (df["Metric"] == selected_metric)
].copy()

tab1, tab2, tab3, tab4 = st.tabs(
    ["Overview", "Bank Comparison", "Rankings", "Raw Data"]
)

with tab1:
    st.subheader("Dashboard Overview")

    col1, col2, col3, col4 = st.columns(4)

    col1.metric("Selected Banks", len(selected_banks))
    col2.metric("Selected Metric", selected_metric)
    col3.metric("Average Value", round(filtered["Value"].mean(), 4))
    col4.metric("Highest Value", round(filtered["Value"].max(), 4))

    st.write("This dashboard compares Small Finance Banks across key financial ratios and performance metrics.")

    fig = px.bar(
        filtered,
        x="Bank",
        y="Value",
        color="Bank",
        title=f"{selected_metric} Comparison"
    )
    st.plotly_chart(fig, use_container_width=True)

with tab2:
    st.subheader("Bank Comparison")

    chart_type = st.radio(
        "Select Chart Type",
        ["Bar Chart", "Line Chart"],
        horizontal=True
    )

    if chart_type == "Bar Chart":
        fig = px.bar(
            filtered,
            x="Bank",
            y="Value",
            color="Bank",
            title=f"{selected_metric} - Bank Wise Comparison"
        )
    else:
        fig = px.line(
            filtered,
            x="Bank",
            y="Value",
            markers=True,
            title=f"{selected_metric} Trend Across Banks"
        )

    st.plotly_chart(fig, use_container_width=True)

    st.subheader("Metric Heatmap")

    heatmap_df = df[df["Bank"].isin(selected_banks)].pivot_table(
        index="Bank",
        columns="Metric",
        values="Value",
        aggfunc="mean"
    )

    fig_heatmap = px.imshow(
        heatmap_df,
        text_auto=True,
        aspect="auto",
        title="Bank vs Metric Heatmap"
    )

    st.plotly_chart(fig_heatmap, use_container_width=True)

with tab3:
    st.subheader("Rankings")

    ranking_df = filtered.sort_values("Value", ascending=False)

    col1, col2 = st.columns(2)

    with col1:
        st.write("Top Banks")
        st.dataframe(ranking_df.head(5), use_container_width=True)

    with col2:
        st.write("Bottom Banks")
        st.dataframe(ranking_df.tail(5), use_container_width=True)

    fig_rank = px.bar(
        ranking_df,
        x="Value",
        y="Bank",
        orientation="h",
        color="Bank",
        title=f"Ranking by {selected_metric}"
    )
    st.plotly_chart(fig_rank, use_container_width=True)

with tab4:
    st.subheader("Raw Data")

    st.dataframe(df, use_container_width=True)

    csv = df.to_csv(index=False).encode("utf-8")

    st.download_button(
        label="Download Data as CSV",
        data=csv,
        file_name="sfb_financial_dashboard_data.csv",
        mime="text/csv"
    )

2026-05-26 05:30:04.672 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:04.676 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:04.679 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:04.680 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:04.688 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:04.689 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:04.692 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:04.694 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:04.695 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:04.696 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:04.699 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:04.700 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:04.701 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:04.702 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:04.704 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:04.704 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:04.706 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:04.707 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:04.708 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:04.709 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:04.718 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:04.719 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:04.721 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:04.722 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:04.724 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:04.725 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:04.727 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:04.727 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:04.729 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:04.729 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:04.730 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:04.732 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:04.733 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:04.734 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:04.736 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:04.737 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:04.740 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:04.741 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:04.742 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:04.743 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:04.745 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:04.747 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:04.748 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:04.749 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:04.749 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:04.751 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:04.755 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:04.758 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:04.832 Please replace `use_container_width` with `width`.

`use_container_width` will be removed after 2025-12-31.

For `use_container_width=True`, use `width='stretch'`. For `use_container_width=False`, use `width='content'`.
2026-05-26 05:30:04.835 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:04.837 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:04.839 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:04.844 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:04.849 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:04.854 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:04.861 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:04.869 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:04.873 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:04.880 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:04.884 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:04.890 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:04.892 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:04.899 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:04.901 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:05.029 Please replace `use_container_width` with `width`.

`use_container_width` will be removed after 2025-12-31.

For `use_container_width=True`, use `width='stretch'`. For `use_container_width=False`, use `width='content'`.
2026-05-26 05:30:05.042 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:05.045 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:05.052 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:05.059 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:05.065 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:05.066 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:05.070 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:05.071 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:05.170 Please replace `use_container_width` with `width`.

`use_container_width` will be removed after 2025-12-31.

For `use_container_width=True`, use `width='stretch'`. For `use_container_width=False`, use `width='content'`.
2026-05-26 05:30:05.173 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:05.176 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:05.177 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:05.180 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:05.181 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:05.183 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:05.185 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:05.186 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:05.189 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:05.191 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:05.192 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:05.193 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:05.193 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:05.197 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:05.199 Please replace `use_container_width` with `width`.

`use_container_width` will be removed after 2025-12-31.

For `use_container_width=True`, use `width='stretch'`. For `use_container_width=False`, use `width='content'`.
2026-05-26 05:30:05.206 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:05.207 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:05.211 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:05.212 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:05.213 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:05.216 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:05.217 Please replace `use_container_width` with `width`.

`use_container_width` will be removed after 2025-12-31.

For `use_container_width=True`, use `width='stretch'`. For `use_container_width=False`, use `width='content'`.
2026-05-26 05:30:05.224 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:05.225 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:05.232 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:05.440 Please replace `use_container_width` with `width`.

`use_container_width` will be removed after 2025-12-31.

For `use_container_width=True`, use `width='stretch'`. For `use_container_width=False`, use `width='content'`.
2026-05-26 05:30:05.451 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:05.454 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:05.455 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:05.458 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:05.468 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:05.475 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:05.481 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:05.484 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:05.490 Please replace `use_container_width` with `width`.

`use_container_width` will be removed after 2025-12-31.

For `use_container_width=True`, use `width='stretch'`. For `use_container_width=False`, use `width='content'`.
2026-05-26 05:30:05.499 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:05.502 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:05.513 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:05.534 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:05.537 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:05.541 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:05.543 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:05.546 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:05.550 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-26 05:30:05.552 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [57]:
!grep -n "st.tabs" app.py

In [58]:
%%writefile app.py
import streamlit as st
import pandas as pd
import plotly.express as px

st.set_page_config(page_title="SFB Financial Dashboard", layout="wide")
st.title("Small Finance Bank Financial Dashboard")

df = pd.read_csv("cleaned_sfb_data.csv")
df["Bank"] = df["Bank"].astype(str).str.strip()
df["Metric"] = df["Metric"].astype(str).str.strip()

selected_banks = st.multiselect(
    "Select Banks",
    options=sorted(df["Bank"].unique()),
    default=sorted(df["Bank"].unique())[:3]
)

selected_metric = st.selectbox(
    "Select Metric",
    options=sorted(df["Metric"].unique())
)

filtered = df[(df["Bank"].isin(selected_banks)) & (df["Metric"] == selected_metric)]

tab1, tab2, tab3, tab4 = st.tabs(["Overview", "Bank Comparison", "Rankings", "Raw Data"])

with tab1:
    st.subheader("Overview")
    col1, col2, col3 = st.columns(3)
    col1.metric("Selected Banks", len(selected_banks))
    col2.metric("Selected Metric", selected_metric)
    col3.metric("Average Value", round(filtered["Value"].mean(), 4))

    fig = px.bar(filtered, x="Bank", y="Value", color="Bank", title=f"{selected_metric} Comparison")
    st.plotly_chart(fig, use_container_width=True)

with tab2:
    st.subheader("Bank Comparison")
    fig = px.bar(filtered, x="Bank", y="Value", color="Bank")
    st.plotly_chart(fig, use_container_width=True)

    heatmap_df = df[df["Bank"].isin(selected_banks)].pivot_table(
        index="Bank", columns="Metric", values="Value", aggfunc="mean"
    )
    fig_heatmap = px.imshow(heatmap_df, text_auto=True, aspect="auto", title="Bank vs Metric Heatmap")
    st.plotly_chart(fig_heatmap, use_container_width=True)

with tab3:
    st.subheader("Rankings")
    ranking_df = filtered.sort_values("Value", ascending=False)
    st.dataframe(ranking_df, use_container_width=True)

with tab4:
    st.subheader("Raw Data")
    st.dataframe(df, use_container_width=True)

Overwriting app.py

In [59]:
!grep -n "st.tabs" app.py

25:tab1, tab2, tab3, tab4 = st.tabs(["Overview", "Bank Comparison", "Rankings", "Raw Data"])

In [60]:
!pkill -f streamlit

In [61]:
!streamlit run app.py --server.port 8501 --server.address 0.0.0.0 --server.headless true > streamlit.log 2>&1 &

In [62]:
!cat streamlit.log

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.

2026-05-26 05:47:30.034 Uvicorn server started on 0.0.0.0:8501

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://172.28.0.12:8501
  External URL: http://35.236.227.192:8501

In [64]:
%%writefile app.py
import streamlit as st
import pandas as pd
import plotly.express as px

st.set_page_config(page_title="SFB Financial Dashboard", layout="wide")
st.title("Small Finance Bank Financial Dashboard")

df = pd.read_csv("cleaned_sfb_data.csv")
df["Bank"] = df["Bank"].astype(str).str.strip()
df["Metric"] = df["Metric"].astype(str).str.strip()

metric_notes = {
    "Revenue growth (YoY)": "Shows year-on-year growth in revenue.",
    "Gross margin": "Shows profitability after direct costs.",
    "EBITDA margin": "Shows operating profitability before interest, tax, depreciation, and amortization.",
    "PBT margin": "Shows profit before tax as a percentage of revenue.",
    "Debt equity ratio": "Shows financial leverage and debt dependency.",
    "ROA": "Shows how efficiently assets generate profit.",
    "ROE": "Shows return generated on shareholders’ equity.",
}

selected_banks = st.multiselect(
    "Select Banks",
    options=sorted(df["Bank"].unique()),
    default=sorted(df["Bank"].unique())
)

selected_metric = st.selectbox(
    "Select Metric",
    options=sorted(df["Metric"].unique())
)

filtered = df[
    (df["Bank"].isin(selected_banks)) &
    (df["Metric"] == selected_metric)
].copy()

filtered = filtered.sort_values("Value", ascending=False)

tab1, tab2, tab3, tab4 = st.tabs(["Overview", "Bank Comparison", "Rankings", "Raw Data"])

with tab1:
    st.subheader("Overview")

    st.info(metric_notes.get(selected_metric, "This metric is used to compare financial performance across banks."))

    top_bank = filtered.iloc[0]["Bank"] if not filtered.empty else "-"
    bottom_bank = filtered.iloc[-1]["Bank"] if not filtered.empty else "-"

    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Selected Banks", len(selected_banks))
    col2.metric("Average Value", round(filtered["Value"].mean(), 4))
    col3.metric("Top Bank", top_bank)
    col4.metric("Bottom Bank", bottom_bank)

    fig = px.bar(
        filtered,
        x="Bank",
        y="Value",
        color="Bank",
        title=f"{selected_metric} Comparison"
    )
    st.plotly_chart(fig, use_container_width=True)

with tab2:
    st.subheader("Bank Comparison")

    fig = px.bar(
        filtered,
        x="Bank",
        y="Value",
        color="Bank",
        title=f"Bank-wise Comparison for {selected_metric}"
    )
    st.plotly_chart(fig, use_container_width=True)

    st.subheader("Metric Heatmap")

    heatmap_df = df[df["Bank"].isin(selected_banks)].pivot_table(
        index="Bank",
        columns="Metric",
        values="Value",
        aggfunc="mean"
    )

    fig_heatmap = px.imshow(
        heatmap_df,
        text_auto=True,
        aspect="auto",
        title="Bank vs Metric Heatmap"
    )
    st.plotly_chart(fig_heatmap, use_container_width=True)

with tab3:
    st.subheader("Rankings")

    col1, col2 = st.columns(2)

    with col1:
        st.write("Top Banks")
        st.dataframe(filtered.head(5), use_container_width=True)

    with col2:
        st.write("Bottom Banks")
        st.dataframe(filtered.tail(5).sort_values("Value"), use_container_width=True)

    fig_rank = px.bar(
        filtered,
        x="Value",
        y="Bank",
        orientation="h",
        color="Bank",
        title=f"Ranking by {selected_metric}"
    )
    st.plotly_chart(fig_rank, use_container_width=True)

with tab4:
    st.subheader("Raw Data")

    st.dataframe(df, use_container_width=True)

    csv = df.to_csv(index=False).encode("utf-8")

    st.download_button(
        label="Download CSV",
        data=csv,
        file_name="sfb_financial_dashboard_data.csv",
        mime="text/csv"
    )

Overwriting app.py

In [65]:
!pkill -f streamlit
!streamlit run app.py --server.port 8501 --server.address 0.0.0.0 --server.headless true > streamlit.log 2>&1 &

In [66]:
!pkill -f streamlit

In [67]:
!streamlit run app.py --server.port 8501 --server.address 0.0.0.0 --server.headless true > streamlit.log 2>&1 &

In [68]:
!cat streamlit.log

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.

2026-05-26 05:53:37.747 Uvicorn server started on 0.0.0.0:8501

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://172.28.0.12:8501
  External URL: http://35.236.227.192:8501

In [ ]:
!./cloudflared tunnel --url http://localhost:8501

2026-05-26T05:53:51Z INF Thank you for trying Cloudflare Tunnel. Doing so, without a Cloudflare account, is a quick way to experiment and try it out. However, be aware that these account-less Tunnels have no uptime guarantee, are subject to the Cloudflare Online Services Terms of Use (https://www.cloudflare.com/website-terms/), and Cloudflare reserves the right to investigate your use of Tunnels for violations of such terms. If you intend to use Tunnels in production you should use a pre-created named tunnel by following: https://developers.cloudflare.com/cloudflare-one/connections/connect-apps
2026-05-26T05:53:51Z INF Requesting new quick Tunnel on trycloudflare.com...
2026-05-26T05:53:56Z INF +--------------------------------------------------------------------------------------------+
2026-05-26T05:53:56Z INF |  Your quick Tunnel has been created! Visit it at (it may take some time to be reachable):  |
2026-05-26T05:53:56Z INF |  https://restricted-graphics-normal-fan.trycloudflare.com                                  |
2026-05-26T05:53:56Z INF +--------------------------------------------------------------------------------------------+
2026-05-26T05:53:56Z INF Cannot determine default configuration path. No file [config.yml config.yaml] in [~/.cloudflared ~/.cloudflare-warp ~/cloudflare-warp /etc/cloudflared /usr/local/etc/cloudflared]
2026-05-26T05:53:56Z INF Version 2026.5.1 (Checksum 3c6a5ba995a258dbe90f98e5fdb2c2620b7be72c3ca761614f6eb52aee252cea)
2026-05-26T05:53:56Z INF GOOS: linux, GOVersion: go1.26.3, GoArch: amd64
2026-05-26T05:53:56Z INF Settings: map[ha-connections:1 protocol:quic url:http://localhost:8501]
2026-05-26T05:53:56Z INF cloudflared will not automatically update when run from the shell. To enable auto-updates, run cloudflared as a service: https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configure-tunnels/local-management/as-a-service/
2026-05-26T05:53:56Z INF Generated Connector ID: 8c4dc750-d3ef-40e0-9d6a-e33f9b2056fa
2026-05-26T05:53:56Z INF Initial protocol quic
2026-05-26T05:53:56Z INF ICMP proxy will use 172.28.0.12 as source for IPv4
2026-05-26T05:53:56Z INF ICMP proxy will use ::1 in zone lo as source for IPv6
2026/05/26 05:53:56 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 7168 kiB, got: 416 kiB). See https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes for details.
2026-05-26T05:53:56Z INF ICMP proxy will use 172.28.0.12 as source for IPv4
2026-05-26T05:53:56Z INF ICMP proxy will use ::1 in zone lo as source for IPv6
2026-05-26T05:53:56Z INF Starting metrics server on 127.0.0.1:20241/metrics
2026-05-26T05:53:56Z INF Tunnel connection curve preferences: [X25519MLKEM768 CurveID(65074) CurveP256] connIndex=0 event=0 ip=198.41.192.67
2026-05-26T05:53:56Z INF Registered tunnel connection connIndex=0 connection=19343a5e-2b9c-44f2-af8e-5ac096cae68b event=0 ip=198.41.192.67 location=iad02 protocol=quic
--- CONNECTIVITY PRE-CHECKS ----------------------------------------------------
COMPONENT         TARGET                     STATUS  DETAILS
DNS Resolution    region1.v2.argotunnel.com  PASS    DNS Resolved successfully
DNS Resolution    region2.v2.argotunnel.com  PASS    DNS Resolved successfully
UDP Connectivity  region1.v2.argotunnel.com  PASS    QUIC connection successful
UDP Connectivity  region2.v2.argotunnel.com  PASS    QUIC connection successful
TCP Connectivity  region1.v2.argotunnel.com  PASS    HTTP/2 connection successful
TCP Connectivity  region2.v2.argotunnel.com  PASS    HTTP/2 connection successful
Cloudflare API    api.cloudflare.com:443     PASS    API is reachable

SUMMARY: Environment is healthy. cloudflared will use 'quic' as primary protocol.
--------------------------------------------------------------------------------

2026-05-26T05:54:02Z INF precheck component="DNS Resolution" details="DNS Resolved successfully" run_id=7d098c18-c469-4750-9b5a-a3a80bb7e996 status=pass target=region1.v2.argotunnel.com
2026-05-26T05:54:02Z INF precheck component="DNS Resolution" details="DNS Resolved successfully" run_id=7d098c18-c469-4750-9b5a-a3a80bb7e996 status=pass target=region2.v2.argotunnel.com
2026-05-26T05:54:02Z INF precheck component="UDP Connectivity" details="QUIC connection successful" run_id=7d098c18-c469-4750-9b5a-a3a80bb7e996 status=pass target=region1.v2.argotunnel.com
2026-05-26T05:54:02Z INF precheck component="UDP Connectivity" details="QUIC connection successful" run_id=7d098c18-c469-4750-9b5a-a3a80bb7e996 status=pass target=region2.v2.argotunnel.com
2026-05-26T05:54:02Z INF precheck component="TCP Connectivity" details="HTTP/2 connection successful" run_id=7d098c18-c469-4750-9b5a-a3a80bb7e996 status=pass target=region1.v2.argotunnel.com
2026-05-26T05:54:02Z INF precheck component="TCP Connectivity" details="HTTP/2 connection successful" run_id=7d098c18-c469-4750-9b5a-a3a80bb7e996 status=pass target=region2.v2.argotunnel.com
2026-05-26T05:54:02Z INF precheck component="Cloudflare API" details="API is reachable" run_id=7d098c18-c469-4750-9b5a-a3a80bb7e996 status=pass target=api.cloudflare.com:443
2026-05-26T05:54:02Z INF precheck complete hard_fail=false run_id=7d098c18-c469-4750-9b5a-a3a80bb7e996 suggested_protocol=quic